[[headers]]
  for = "/_astro/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Cache-Control = "public, max-age=31536000, immutable"

[build]
  command = "astro build"
  publish = "dist/"

  [[redirects]]
    from = "/contact"
    to = "/"

  [[redirects]]
    from = "/about"
    to = "/"